server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 10m
spring:
  messages:
    basename: messages/message
    encoding: utf-8
    cache-duration: 10
    fallback-to-system-locale: false
#spring:
  session:
    redis:
      namespace: spring:session
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: aaaa
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://springboot2.cfsyc26eox2y.ap-northeast-2.rds.amazonaws.com:3306/shopdb?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:log4jdbc:mysql://springboot2.cfsyc26eox2y.ap-northeast-2.rds.amazonaws.com/shopdb?characterEncoding=utf8
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul

    # user01/111111
    username: ENC(pkXtsT1k8PPq9YNsFgvGFw==)
    password: ENC(0jDz7THv5b/EpvzM7GtN/g==)
mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: error
app:
  url:
    server-url: http://172.16.21.235:81
    chatbot-url: http://172.16.21.235
  dir:
    imgdir: file:/root/imgs/ # 화면 출력용
    uploadimgdir: /root/imgs/  # 파일 업로드용
    logdir: file:/root/logs/
  key:
    wkey: ENC(B1Xa3fUX6q9cqbIT0zHIn15BEUG48YPcD+Mt9Dcb31XJ+Dx6DPDFLxXcrTc+SXTwuVIEl2cW9NwRBoVTPl6wzJ1AUyaq4PSHi7gB2EQRaFdL37o3nNS5y4zQhRqfFuJUnkEZMEUi148G87SXHWEBNBWlgWY1lqUA)
    whkey: ENC(7EzilONGcryPAgyC/hbMJrxKmRQBi2/wn0THf3fUeTHUl+YspN6jSJmv3chkeRcq)
    ncp-id: ptf9npiajc
    ncp-secret: ENC(upoi7px28RUeFP2y80UXh5Zv6nMXw85/bMhDx066JFjf+ZoBUAocdWIW0HgCW7q9zQgIZ5AZobs=)
    chatbot_url: ENC(EOH6OJem2GudtleU2tPyuusYJOBImsK4Z8zT7xMy5vqLti/wlilWHnXzlQ8gACDFsqZQ68o1u1144hFgPZfEEkMubF/MZcRZ2vnd/bflge6VGf83H/lGy7zp9BGMIB21sWyyjGELAu/MnH88ga0wXkEiddaIKn2N8xFZOok2Pck=)
    chatbot_key: ENC(wmUrbX3IWdQGBjfOD+xheez4KYNbDpf81xugVDzvfX8hoKKXTCdd+7uc6uYeXLpuH0qt8jj1fqg=)
    kakao_rest_key: ENC(X8MBCnpuGZB7vp1nLMf/oxc8SYQ4awzA8iKSR0rpAuifBr5zEXHB1BHg+DwMd8Sn)